### ISSUE TITLE
clj-yaml (snake-yaml, really) chokes on!!python/tuple

### ISSUE THREAD

**Issue by kenrestivo-stem** [circleci/clj-yaml#21] opened 2018-07-31 16:24 UTC
Trying to parse:

```yml
baz_types: !!python/tuple [foo, bar]
```

Explodes as follows:
```
                                                 clj-yaml.core/parse-string                                           core.clj:  120
                                                                        ...                                                         
                                               org.yaml.snakeyaml.Yaml.load                                          Yaml.java:  400
                                     org.yaml.snakeyaml.Yaml.loadFromReader                                          Yaml.java:  481
               org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData                               BaseConstructor.java:  127
           org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument                               BaseConstructor.java:  141
             org.yaml.snakeyaml.constructor.BaseConstructor.constructObject                               BaseConstructor.java:  182
  org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct                               SafeConstructor.java:  442
           org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence                               BaseConstructor.java:  246
      org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2                               BaseConstructor.java:  275
             org.yaml.snakeyaml.constructor.BaseConstructor.constructObject                               BaseConstructor.java:  182
  org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct                               SafeConstructor.java:  461
            org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping                               BaseConstructor.java:  354
     org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep                               SafeConstructor.java:  145
     org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep                               BaseConstructor.java:  373
             org.yaml.snakeyaml.constructor.BaseConstructor.constructObject                               BaseConstructor.java:  182
  org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct                               SafeConstructor.java:  461
            org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping                               BaseConstructor.java:  354
     org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep                               SafeConstructor.java:  145
     org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep                               BaseConstructor.java:  373
             org.yaml.snakeyaml.constructor.BaseConstructor.constructObject                               BaseConstructor.java:  182
  org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct                               SafeConstructor.java:  442
           org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence                               BaseConstructor.java:  246
      org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2                               BaseConstructor.java:  275
             org.yaml.snakeyaml.constructor.BaseConstructor.constructObject                               BaseConstructor.java:  182
  org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct                               SafeConstructor.java:  461
            org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping                               BaseConstructor.java:  354
     org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep                               SafeConstructor.java:  145
     org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep                               BaseConstructor.java:  373
             org.yaml.snakeyaml.constructor.BaseConstructor.constructObject                               BaseConstructor.java:  182
  org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct                               SafeConstructor.java:  461
            org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping                               BaseConstructor.java:  354
     org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep                               SafeConstructor.java:  145
     org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep                               BaseConstructor.java:  373
             org.yaml.snakeyaml.constructor.BaseConstructor.constructObject                               BaseConstructor.java:  182
org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct                               SafeConstructor.java:  477
org.yaml.snakeyaml.constructor.ConstructorException: null; could not determine a constructor for the tag tag:yaml.org,2002:python/tuple;  in 'string', line 33, column 28:
                                                                   baz_types: !!python/tuple [foo, bar]
                                                                                    ^
        problem: "could not determine a constructor for the tag tag:yaml.org,2002:python/tuple"
    problemMark: #object[org.yaml.snakeyaml.error.Mark 0x76fef7d8 " in 'string', line 33, column 28:\n              baz_types: !!python/tuple [foo, bar]\n                               ^"]

```

**Comment by kenrestivo-stem** [comment] 2018-07-31 16:28
Upstream problem, seems to be: https://bitbucket.org/asomov/snakeyaml/issues/410/snakeyaml-chokes-onpython-tuple

**Comment by marcomorain** [comment] 2018-07-31 16:30
Hi @kenrestivo-stem - the library is behaving as intended - I think the error is clear from the exception message`problem: "could not determine a constructor for the tag tag:yaml.org,2002:python/tuple"`.

The documentation that you need is here: https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-constructors-representers-resolvers

I'm going to close this for now.

**Closed by marcomorain** 2018-07-31 16:30 UTC

**Comment by kenrestivo-stem** [comment] 2018-07-31 16:58
Thanks, culprit appears to be https://docs.openstack.org/infra/jenkins-job-builder/
